version: '3.8'

services:
  angular-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: angular-dev
    ports:
      - "4200:4200"
    volumes:
      - ./src:/app/src
      - ./angular.json:/app/angular.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.app.json:/app/tsconfig.app.json
      - ./package.json:/app/package.json
      - /app/node_modules
    command: nodemon --watch src --ext ts,json,html,scss --exec "ng serve --host 0.0.0.0 --poll 2000"
