version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-app
    ports:
      - "4200:80" # Map container's Nginx port 80 to your local 4200
    restart: unless-stopped